# Generated by Django 3.2.9 on 2021-11-20 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useracc_api', '0003_alter_user_user_foods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_foods',
        ),
    ]
